# Generated by Django 5.2 on 2025-05-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.TextField(blank=True, null=True, verbose_name='Калорийность'),
        ),
    ]
