# Generated by Django 5.2 on 2025-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_short_description_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='semi_finished_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок хранения (часов)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок хранения (дней)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)'),
        ),
    ]
