# Generated by Django 5.2.2 on 2025-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_semi_finished_hours_product_shelf_life_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(verbose_name='Изображение'),
        ),
    ]
